import { StyleSheet } from "react-native";
import { MD3Theme } from "react-native-paper";

export const commissionsStyles = (theme: MD3Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scrollView: {
      flex: 1,
    },
    tabContainer: {
      flexDirection: "row",
      paddingHorizontal: 16,
      paddingVertical: 8,
      paddingTop: 16,
      backgroundColor: theme.colors.background,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.outline,
      marginBottom: 8,
    },
    tab: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      backgroundColor: "transparent",
    },
    activeTab: {
      backgroundColor: theme.colors.primary,
    },
    tabText: {
      fontSize: 15,
      fontWeight: "500",
      color: theme.colors.onSurfaceVariant,
    },
    activeTabText: {
      color: theme.colors.onPrimary,
      fontWeight: "600",
    },
    metricsScrollView: {
      marginVertical: 16,
    },
    metricsScrollContainer: {
      paddingLeft: 0,
      paddingRight: 16,
      gap: 12,
    },
    metricsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
      marginVertical: 16,
    },
    metricCard: {
      padding: 14,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.outline,
      minHeight: 96,
      overflow: "hidden",
    },
    ticketMetricCard: {
      width: 178,
      marginRight: 0,
      minHeight: 96,
    },
    metricTitle: {
      fontSize: 12,
      color: theme.colors.onSurfaceVariant,
      marginBottom: 8,
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    metricValueRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    metricIcon: {
      marginLeft: 8,
      opacity: 0.8,
    },
    metricValue: {
      fontSize: 24,
      fontWeight: "700",
      color: theme.colors.onSurface,
    },
    metricChange: {
      fontSize: 12,
      marginTop: 4,
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.dark ? "rgba(255,255,255,0.05)" : "#FFFFFF",
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.dark
        ? "rgba(255,255,255,0.10)"
        : "rgba(15,23,42,0.10)",
      paddingHorizontal: 12,
      marginBottom: 16,
    },
    searchIcon: {
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      paddingVertical: 12,
      fontSize: 15,
      color: theme.colors.onSurface,
    },
    searchFab: {
      position: "absolute",
      right: 22,
      width: 48,
      height: 48,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      zIndex: 19,
      elevation: 19,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
    },
    searchActiveDot: {
      position: "absolute",
      top: 10,
      right: 10,
      width: 8,
      height: 8,
      borderRadius: 999,
      backgroundColor: "#EF4444",
      borderWidth: 1,
      borderColor: theme.colors.background,
    },
    searchModalRoot: {
      flex: 1,
      justifyContent: "flex-end",
    },
    searchBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: theme.dark ? "rgba(0,0,0,0.36)" : "rgba(15,23,42,0.22)",
    },
    searchPanel: {
      marginHorizontal: 16,
      marginBottom: 12,
      minHeight: 56,
      borderRadius: 18,
      borderWidth: 1,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: theme.dark ? "#000000" : "#6366F1",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: theme.dark ? 0.28 : 0.16,
      shadowRadius: 18,
      elevation: 12,
    },
    searchPanelAction: {
      minWidth: 38,
      minHeight: 38,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
    },
    searchDoneText: {
      fontSize: 13,
      fontWeight: "800",
    },
    contentCard: {
      backgroundColor: "transparent",
      borderRadius: 12,
      padding: 0,
      marginBottom: 16,
      borderWidth: 0,
      borderColor: "transparent",
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.colors.onSurface,
      marginBottom: 4,
    },
    cardSubtitle: {
      fontSize: 13,
      color: theme.colors.onSurfaceVariant,
      marginBottom: 10,
    },
    commissionItem: {
      backgroundColor: theme.dark ? "rgba(255,255,255,0.04)" : "#FFFFFF",
      padding: 14,
      borderRadius: 18,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: theme.dark
        ? "rgba(255,255,255,0.09)"
        : "rgba(99,102,241,0.12)",
      overflow: "hidden",
      shadowColor: theme.dark ? "#000000" : "#6366F1",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: theme.dark ? 0.18 : 0.08,
      shadowRadius: 12,
      elevation: 2,
    },
    cardTopAccent: {
      position: "absolute",
      top: 0,
      left: 18,
      right: 18,
      height: 1.5,
    },
    commissionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 12,
    },
    applicationId: {
      fontSize: 15,
      fontWeight: "700",
      color: theme.colors.onSurface,
      marginBottom: 4,
    },
    lenderName: {
      fontSize: 13,
      color: theme.colors.onSurfaceVariant,
    },
    statusBadge: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      borderWidth: 1,
    },
    statusText: {
      fontSize: 12,
      fontWeight: "600",
    },
    detailRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 7,
      borderBottomWidth: 1,
      borderBottomColor: theme.dark
        ? "rgba(255,255,255,0.06)"
        : "rgba(15,23,42,0.06)",
    },
    detailLabel: {
      fontSize: 13,
      color: theme.colors.onSurfaceVariant,
    },
    detailValue: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.colors.onSurface,
    },
    dateRow: {
      marginTop: 10,
      paddingTop: 0,
      borderTopWidth: 0,
      borderTopColor: "transparent",
    },
    dateText: {
      fontSize: 12,
      color: theme.colors.onSurfaceVariant,
    },
    emptyState: {
      alignItems: "center",
      paddingVertical: 40,
    },
    emptyStateText: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.colors.onSurface,
      marginBottom: 4,
    },
    emptyStateSubtext: {
      fontSize: 13,
      color: theme.colors.onSurfaceVariant,
    },
    retryButton: {
      marginTop: 12,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.primary,
      backgroundColor: theme.dark
        ? "rgba(99,102,241,0.16)"
        : "rgba(99,102,241,0.10)",
    },
    retryButtonText: {
      color: theme.colors.primary,
      fontSize: 13,
      fontWeight: "700",
    },
    paginationRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 12,
      paddingTop: 10,
      borderTopWidth: 1,
      gap: 8,
    },
    rowsControl: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      flexShrink: 1,
    },
    rowsLabel: {
      fontSize: 12,
      color: theme.colors.onSurfaceVariant,
    },
    rowsInput: {
      minWidth: 42,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderWidth: 1,
      borderRadius: 7,
      textAlign: "center",
      fontSize: 12,
      fontWeight: "600",
    },
    pageControl: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    pageButton: {
      width: 28,
      height: 28,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    createFabWrap: {
      position: "absolute",
      right: 18,
      bottom: 22,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 20,
      elevation: 20,
    },
    createFabPulse: {
      position: "absolute",
      width: 82,
      height: 48,
      borderRadius: 999,
    },
    createFab: {
      minWidth: 82,
      height: 48,
      borderRadius: 999,
      paddingHorizontal: 20,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.36,
      shadowRadius: 18,
      elevation: 10,
    },
    createFabText: {
      color: theme.colors.onPrimary,
      fontSize: 14,
      fontWeight: "800",
    },
  });
