import { StyleSheet } from "react-native";
import type { MD3Theme } from "react-native-paper";

export const createBankerStyles = (theme: MD3Theme) =>
  StyleSheet.create({
    // ── Selection screen ──
    selectionRoot: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    selHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: theme.dark ? "#334155" : "#F1F5F9",
    },
    backBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.dark ? "#0F172A" : "#F8FAFC",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.dark ? "#334155" : "#E2E8F0",
    },
    selTitle: {
      fontSize: 20,
      fontWeight: "800",
      color: theme.colors.onSurface,
      letterSpacing: -0.5,
    },
    selSubtitle: {
      fontSize: 12,
      color: theme.colors.onSurfaceVariant,
      marginTop: 2,
      fontWeight: "500",
    },
    selIconBox: {
      width: 44,
      height: 44,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    selSearchWrap: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginHorizontal: 16,
      marginTop: 14,
      marginBottom: 4,
      backgroundColor: theme.dark ? "#0F172A" : "#F8FAFC",
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.dark ? "#334155" : "#E2E8F0",
      paddingHorizontal: 14,
      paddingVertical: 11,
    },
    selSearchInput: {
      flex: 1,
      fontSize: 15,
      color: theme.colors.onSurface,
      fontWeight: "500",
      paddingVertical: 0,
    },
    selCountRow: {
      paddingHorizontal: 20,
      paddingVertical: 8,
    },
    selCountText: {
      fontSize: 12,
      color: theme.dark ? "#fff" : theme.colors.onSurfaceVariant,
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    selListContent: {
      paddingHorizontal: 16,
      paddingBottom: 32,
    },
    selItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 13,
      paddingVertical: 14,
    },
    selItemIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    selItemLabel: {
      flex: 1,
      fontSize: 15,
      fontWeight: "600",
      color: theme.colors.onSurface,
    },
    selBankBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
      borderWidth: 1,
    },
    selBankBadgeText: {
      fontSize: 11,
      fontWeight: "700",
    },
    selSep: {
      height: 1,
      backgroundColor: theme.dark ? "#334155" : "#F1F5F9",
      marginLeft: 49,
    },

    // ── Results / main screen ──
    selectionStateBox: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 28,
      paddingBottom: 72,
    },
    selectionStateTitle: {
      marginTop: 12,
      fontSize: 16,
      fontWeight: "800",
      color: theme.colors.onSurface,
      textAlign: "center",
    },
    selectionStateText: {
      marginTop: 8,
      fontSize: 13,
      lineHeight: 19,
      color: theme.colors.onSurfaceVariant,
      fontWeight: "500",
      textAlign: "center",
    },
    selectionRetryBtn: {
      marginTop: 18,
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: theme.colors.primary,
    },
    selectionRetryText: {
      fontSize: 13,
      fontWeight: "800",
      color: "#fff",
    },

    root: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    pageHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 10,
      backgroundColor: theme.colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: theme.dark ? "#334155" : "#F1F5F9",
    },
    pageTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: theme.dark ? "#fff" : theme.colors.onSurface,
      letterSpacing: -0.4,
    },
    pageSubtitle: {
      fontSize: 11,
      color: theme.colors.onSurfaceVariant,
      marginTop: 1,
      fontWeight: "500",
    },
    resetBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      backgroundColor: theme.dark ? "#1D4ED8" : "#EFF6FF",
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.dark ? "#1E40AF" : "#BFDBFE",
    },
    resetText: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.dark ? "#fff" : theme.colors.primary,
    },

    // ── Breadcrumb ──
    breadcrumbRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: 6,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 4,
    },
    pill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      backgroundColor: theme.dark ? "#0F172A" : "#EFF6FF",
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderWidth: 1,
      borderColor: theme.dark ? "#334155" : "#BFDBFE",
    },
    pillBank: {
      backgroundColor: theme.dark ? "#111827" : "#F5F3FF",
      borderColor: theme.dark ? "#4338CA" : "#C4B5FD",
    },
    pillCity: {
      backgroundColor: theme.dark ? "#081C15" : "#ECFDF5",
      borderColor: theme.dark ? "#065F46" : "#A7F3D0",
    },
    pillText: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.dark ? "#fff" : theme.colors.primary,
    },

    // ── DSA Card ──
    dsaCard: {
      marginHorizontal: 16,
      marginTop: 12,
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.dark ? "#4338CA" : "#E9D5FF",
      overflow: "hidden",
    },
    dsaHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 14,
      paddingVertical: 13,
      backgroundColor: theme.dark ? "#111827" : "#FAFAFF",
    },
    dsaHeaderLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    dsaHeaderText: {
      fontSize: 13,
      fontWeight: "700",
      color: theme.dark ? "#fff" : theme.colors.primary,
    },
    dsaHeaderRight: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    dsaSeeText: {
      fontSize: 12,
      fontWeight: "600",
      color: theme.dark ? "#fff" : theme.colors.primary,
    },
    dsaBody: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      backgroundColor: theme.colors.surface,
    },
    dsaRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 8,
    },
    dsaLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    dsaLabel: {
      fontSize: 12,
      color: theme.colors.onSurfaceVariant,
      fontWeight: "500",
    },
    dsaBankName: {
      fontSize: 13,
      fontWeight: "700",
      color: theme.colors.onSurface,
    },
    dsaDivider: {
      height: 1,
      backgroundColor: theme.dark ? "#334155" : "#F1F5F9",
    },
    dsaCodeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: theme.dark ? "#1E3A8A" : "#F5F3FF",
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.dark ? "#4338CA" : "#DDD6FE",
    },
    dsaCodeText: {
      fontSize: 13,
      fontWeight: "800",
      color: theme.dark ? "#fff" : theme.colors.primary,
      letterSpacing: 0.5,
    },
    dsaCopyBtn: {
      padding: 2,
    },
    dsaPartner: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.colors.onSurface,
    },

    // ── Results header ──
    listContent: {
      paddingBottom: 32,
    },
    resultsHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 10,
    },
    resultsLocation: {
      fontSize: 16,
      fontWeight: "800",
      color: theme.dark ? "#fff" : theme.colors.onSurface,
      letterSpacing: -0.3,
    },
    countBadge: {
      backgroundColor: theme.dark ? "#1E3A8A" : "#EFF6FF",
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.dark ? "#1E40AF" : "#BFDBFE",
    },
    countText: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.dark ? "#fff" : theme.colors.primary,
    },

    // ── Card ──
    card: {
      flexDirection: "row",
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.dark ? "#334155" : "#F1F5F9",
      marginHorizontal: 16,
    },
    cardStripe: { width: 4 },
    cardBody: { flex: 1, padding: 13 },
    cardTopRow: { flexDirection: "row", alignItems: "center", gap: 11 },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.dark ? "#1E293B" : "#E2E8F0",
    },
    avatarLetter: {
      fontSize: 18,
      fontWeight: "800",
      color: theme.colors.onSurface,
    },
    cardMeta: { flex: 1 },
    bankerName: {
      fontSize: 15,
      fontWeight: "700",
      color: theme.colors.onSurface,
      letterSpacing: -0.2,
    },
    locationRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      marginTop: 2,
    },
    locationText: {
      fontSize: 11,
      color: theme.colors.onSurfaceVariant,
      fontWeight: "500",
    },
    actionBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.dark ? "#0F172A" : "#EFF6FF",
    },

    emailRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 10,
      gap: 6,
    },
    emailPill: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: theme.dark ? "#0F172A" : "#F8FAFC",
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.dark ? "#334155" : "#E2E8F0",
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    emailAddress: {
      flex: 1,
      fontSize: 12,
      color: theme.colors.onSurface,
      fontWeight: "500",
    },
    emailIconBtn: {
      width: 32,
      height: 32,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.dark ? "#0F172A" : "#F1F5F9",
      borderWidth: 1,
      borderColor: theme.dark ? "#334155" : "#E2E8F0",
    },
    emailSendBtn: {
      backgroundColor: theme.dark ? "#1E3A8A" : "#EFF6FF",
      borderColor: theme.dark ? "#1E40AF" : "#BFDBFE",
    },

    chipsRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 10 },
    specChip: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      paddingHorizontal: 9,
      paddingVertical: 4,
      borderRadius: 20,
      gap: 5,
      backgroundColor: theme.dark ? "#1E293B" : "#EEF2FF",
    },
    specDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.colors.primary,
    },
    specLabel: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.colors.onSurface,
    },
    bankChip: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      paddingHorizontal: 9,
      paddingVertical: 4,
      borderRadius: 20,
      borderWidth: 1,
      gap: 5,
      borderColor: theme.dark ? "#334155" : "#E2E8F0",
      backgroundColor: theme.dark ? "#0F172A" : "#F8FAFC",
    },
    bankLabel: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.colors.onSurface,
    },

    // ── Empty ──
    emptyBox: { alignItems: "center", marginTop: 64, gap: 8 },
    emptyIcon: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: theme.dark ? "#0F172A" : "#F8FAFC",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 4,
      borderWidth: 1,
      borderColor: theme.dark ? "#334155" : "#E2E8F0",
    },
    emptyTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: theme.colors.onSurfaceVariant,
    },
    emptySub: {
      fontSize: 13,
      color: theme.colors.onSurfaceVariant,
      fontWeight: "500",
    },
  });
